server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000

          inventory-service:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: basic

logging:
  level:
    ru.yandex.practicum.order.feign.InventoryClient: DEBUG