@namespace("ru.yandex.practicum.kafka.telemetry.event")
protocol SensorEventProtocol {

  record ClimateSensorAvro {
    int co2_level;
    int humidity;
    int temperature_c;
  }

  record LightSensorAvro {
    int luminosity;
    int link_quality;
  }

  record MotionSensorAvro {
    int voltage;
    boolean motion;
    int link_quality;
  }

  record SwitchSensorAvro {
    boolean state;
  }

  record TemperatureSensorAvro {
    int temperature_f;
    int temperature_c;
  }

  record SensorEventAvro {
    string id;
    string hub_id;
    long timestamp;
    union { null, ClimateSensorAvro, LightSensorAvro, MotionSensorAvro, SwitchSensorAvro, TemperatureSensorAvro } payload;
  }
}