spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      hub-events:
        group-id: analyzer-hub-events-group
        auto-offset-reset: earliest
        enable-auto-commit: false
        max-poll-records: 100
        topic: telemetry.hubs.v1
      snapshots:
        group-id: analyzer-snapshots-group
        auto-offset-reset: earliest
        enable-auto-commit: false
        max-poll-records: 50
        topic: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum: DEBUG
    net.devh.boot.grpc: DEBUG